name: Collate Builds

agent:
  type: Unity::VM
  image: cds-ops/ubuntu-18.04-agent:v1.0.11-765607
  flavor: b1.large

dependencies:
  - .yamato/Build Android.yml
  - .yamato/Build Linux x64.yml
  - .yamato/Build Classlibs OSX.yml
  - .yamato/Build Runtime OSX.yml
  - .yamato/Build Windows x64.yml
  - .yamato/Build Windows x86.yml
  
commands:
  - .yamato/scripts/collate_builds.sh

triggers:
  pull_requests:
    - targets:
        only:
          - "unity-master"
  cancel_old_ci: true
  recurring:
    - branch: unity-master-new-unitychanges
      frequency: daily # Should run between midnight and 6AM UTC

artifacts: 
  builds:
    paths:
      - collectedbuilds/builds.7z
  stevedore:
    paths:
      - stevedore/MonoBleedingEdge.7z
      - stevedore/artifactid.txt
